[versions]
jakarta-servlet-api = "6.1.0"
springframework = "6.2.7"

[libraries]
jakarta-servlet = { group = "jakarta.servlet", name = "jakarta.servlet-api", version.ref = "jakarta-servlet-api" }
spring-webmvc = { group = "org.springframework", name = "spring-webmvc", version.ref = "springframework" }
